modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]

modId = "${mod_id}"
version = "1.0"
displayName = "Alpha Test"
logoFile="strong_love.png"
updateJSONURL = ""

description = '''
Authors:
- §dLinnett§r

Musicians:

Art/Idea-makers:
- §bLinnett§r

Trunslations:


'''


[[dependencies."${mod_id}"]]

modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]

modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"